- name: create flowdesign bak dir
  file: path={{flowdesign_path}}/../bak state=directory owner=k007 group=k007 mode=0755
- name: bakup flowdesign
  shell: |
    tar -zcvf {{flowdesign_path}}_`date '+%Y_%m_%d'`.tar.gz {{flowdesign_path}}/dist
    mv {{flowdesign_path}}_`date '+%Y_%m_%d'`.tar.gz {{flowdesign_path}}/../bak
    rm -rf {{flowdesign_path}}/dist
- name: copy flowdesign package
  unarchive: src={{flowdesign_service}}.tar.gz dest={{flowdesign_path}}
- name:
  shell:
    sleep 5

#- name: replace flowdesign profile
#  replace:
#    path: "{{flowdesign_path}}/dist/install.sh"
#    regexp: "k007-te.baifendian.com"
#    replace: "da.cisp.com"
#    backup: yes
- name: copy templates
  template: src="templates/flowdesign_dns_update.sh" dest={{flowdesign_path}}/dist owner=k007 group=k007 mode=0644


- name: chown
  shell: |
    chown k007:k007 {{base_path}} -R

- name: start flowdesign service
  ignore_errors: True
  shell: |
    cd {{flowdesign_path}}/dist/
    /bin/sh flowdesign_dns_update.sh
