cluster.name: {{cluster_name}}
node.name: {{ansible_hostname}} 
node.master: 
node.data: 
path.data: {{path_data}}
path.logs: {{path_logs}}
network.host: {{hostvars[inventory_hostname].ansible_default_ipv4.address}}
http.port: 9200
transport.tcp.port: 9300
discovery.zen.ping.unicast.hosts: {{unicast_hosts}}
discovery.zen.minimum_master_nodes: {{minimum_master_nodes}}
http.cors.enabled: true
http.cors.allow-origin: "*"
bootstrap.system_call_filter: false
